### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/disco#1]
0.3.0

- [x] (breaking) Change `item_id` to `user_id` for `similar_users`
- [x] (breaking) Change warning to an error when `value` passed
- [x] (breaking, maybe) Make Faiss the default library (and possibly remove support for NGT)
- [x] Remove `wilson_score` dependency for `top_items` (slightly different calculation, just needs uncommented)
- [x] Drop support for Ruby < 2.6

**Comment by librod89** [comment]
Another nice addition would be to return recommendations over a certain score. Something like:

`recommender.item_recs(item_id, score: .95)`

**Comment by ankane** [comment]
Hey @librod89, thanks for the suggestion! You can currently do `recommender.item_recs(item_id, count: nil).select { |v| v[:score] >= 0.95 }`, so want to hold off on adding another option for now.

**Comment by gmverdon** [comment]
I've implemented the disco recommendations in my production app, it works like a charm, thank you immensely for this gem and your efforts @ankane! 

One big improvement would be that the recommender would take into account the date when recommending. My recommendations differ per season, but now the recommender doesn't show different recommendations in the winter compared to the summer. How can I achieve this?

**Comment by ankane** [comment]
Hey @gmverdon, I don't have any experience with seasonal recommendations. You could try dividing the data and creating a separate recommender for each season with Disco, or if you find an approach that supports seasonality, use a library like [XLearn](https://github.com/ankane/xlearn) or [Torch.rb](https://github.com/ankane/torch.rb) to implement it.
