### ISSUE TITLE
Attributes in different model

### ISSUE THREAD

**Issue by Shalashtein** [ankane/disco#10]
Hi,

This looks great, I appreciate the effort, I stumbled upon this gem while I was planning my own recommendation engine. I've got data about my products that's stored in different models, everything from the number of times the item has been viewed, how the user interacted with it, whether they purchased it, its raking etc.

Can I use this gem to fit that data? Is there a wiki or a tutorial of something like that? Is there a more comprehensive documentation for this gem somewhere?

**Comment by ankane** [comment]
Hey @Shalashtein, the readme should have all the documentation/features. If you have data for multiple types of interactions, you'll probably want to use a different model to fit the data. There's also [cmfrec](https://github.com/ankane/cmfrec), which can fit a single type of interaction data + side information about users and items.
