### ISSUE TITLE
Building a Hybrid Approach

### ISSUE THREAD

**Issue by jesster2k10** [ankane/disco#11]
Hey, thanks for this library! I'm trying to work out how I could go about building a hybrid recommendation system that combines collaborative filtering, content based filtering and also knowledge based recommendations rather than one of them exclusively.
Do you have any suggestions how to go about this, or where to start? I've read through the README and you suggested using the https://github.com/jpmckinney/tf-idf-similarity gem for content-based recommendations to remedy the cold-start issue; but how would this look like in a real-world example as a hybrid system?

**Comment by ankane** [comment]
Hey @jesster2k10, the simplest hybrid approach would be to use Disco for user-based and/or item-based recommendations and tf-idf-similarity or similar for content-based recommendations, and then show users recommendations from each method. You can use `has_recommended` to store recommendations generated from any method.
