### ISSUE TITLE
Value param not working for Implicit feedback

### ISSUE THREAD

**Issue by jcalem** [ankane/disco#13]
I've been using this recommendation engine for implicit feedback and It seems like the value param isn't doing anything. 

For example:
```
recommender.fit([
  {user_id: 1, item_id: 1, value: 1.0},
  {user_id: 2, item_id: 1, value: 1.0},
  {user_id: 2, item_id: 2, value: 1.0},
  {user_id: 2, item_id: 3, value: 0.0}
])
```
yields the same result as:
```
recommender.fit([
  {user_id: 1, item_id: 1, value: 1.0},
  {user_id: 2, item_id: 1, value: 1.0},
  {user_id: 2, item_id: 2, value: 1.0},
  {user_id: 2, item_id: 3, value: 1.0}
])
```
A higher value should indicate a stronger preference but that doesn't appear to be happening in any examples I try.

**Comment by ankane** [comment]
Hey @jcalem, thanks for reporting! It looks like the value is always 1 for one-class matrix factorization in the underlying library. I should have caught this (facepalm).

For next steps, will:

1. Remove `value` from the docs
2. Release a new version with a warning if `value` is set
3. Change the warning to an error in 0.3.0

If you do need this functionality, [cmfrec](https://github.com/ankane/cmfrec) has it (and has very similarity API).

**Comment by jcalem** [comment]
It happens. I’ll switch over to the other library. Thank you for your help!

**Comment by ankane** [comment]
Just finished steps 1 and 2. Thanks again for finding this!
