### ISSUE TITLE
Couple of clarifications

### ISSUE THREAD

**Issue by Ashwin-op** [ankane/disco#16]
1. Are there any minimum hardware requirements to implement this gem?
2. RIght now I'm using Ruby 2.5.x in a project (that's in production), #1 says the support for Ruby < 2.6 will be removed, will it happen in the near future?
3. Will the gem be maintained for a couple of years?
4. Are there are benchmarks or statistics on the working of the gem?

**Comment by ankane** [comment]
Hey @Ashwin-op,

1. I'm not aware of any, but you'll probably want enough physical memory to fit your data
2. Probably, as I only plan to support non-EOL Ruby versions
3. I can't make any promises on maintenance
4. I don't have any benchmarks, but feel free to share if you create some

**Comment by Ashwin-op** [comment]
Thanks for your response!
