### ISSUE TITLE
Storing recommendations in Redis

### ISSUE THREAD

**Issue by Ashwin-op** [ankane/disco#17]
[Here](https://github.com/ankane/disco#storing-recommenders) it has been mentioned that we can store the recommender to a file, database, or any other storage system.

Can we also save the `.bin` file to Redis and perform recommendations?

**Comment by ankane** [comment]
Hey @Ashwin-op, you can store the recommender in any storage system, including Redis. Instead of `File.binwrite("recommender.bin", bin)`, use `redis.set("recommender", bin)`.

**Comment by Ashwin-op** [comment]
And since `bin` is an `IO` we need to convert it into a string to store it right?

**Comment by ankane** [comment]
Hey @Ashwin-op, you can check the Ruby type with:

```ruby
bin = Marshal.dump(recommender)
puts bin.class.name
```
