### ISSUE TITLE
Updating recommendations

### ISSUE THREAD

**Issue by Ashwin-op** [ankane/disco#18]
Is there a way we can update the model after fitting it once, like
- I collect the `data`
- Perform `recommender.fit(data)` and build the model
- Now if I get some `new_data` or the `rating` between an `item` and a `user` changes
- If I perform `recommender.fit(new_data)`, then the old `user_factors` and `item_factors` gets overwritten by the new one and the score becomes `NaN` for many items

Anyway to resolve that or perform incremental model updates?

**Comment by ankane** [comment]
Hey @Ashwin-op, check out #7.
