### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by pascalbetz** [ankane/disco#19]
Not an Issue but a Questions. If you have another place to discuss questions, then of course I'll move it there. 

The discussion in https://github.com/ankane/disco/issues/1 suggests that the `score` is normalized to 0..1?
I did a quick example and this does not seem to be the case for me. Is there something I need to consider to have normalized scores?

Is there a built in way to store/retrieve "simiilar users" for ActiveRecord? If not is this something that would be welcome or even make sense as a PR?

Thanks for the fantastic library. I was able to implement a recommendation system in no time.

**Comment by ankane** [comment]
Hey @pascalbetz, can you share more details/an example of what you're seeing with scores?

For similar users, you should be able to store them the same as item recommendations (`has_recommended :users` / `update_recommended_users`). When 0.3.0 is released, you'll likely need to map the `:user_id` key to `:item_id` before passing to `update_recommended_users`.

**Comment by pascalbetz** [comment]
Thanks, the `similar_user` hint worked like charm. did not see the trees for the forest, it seems.

About the scores:


I have about 4k data points like this:

```
[
  {:user_id=>10951, :item_id=>1906, :rating=>5}, 
  {:user_id=>971, :item_id=>683, :rating=>10}, 
  {:user_id=>556, :item_id=>1629, :rating=>7}, 
  {:user_id=>10383, :item_id=>1313, :rating=>7},
  {:user_id=>10798, :item_id=>1388, :rating=>4},
]
```

**Comment by ankane** [comment]
Scores are only normalized for `item_recs` and `similar_users`. For `user_recs` with explicit feedback, the `score` is the predicted rating.

**Comment by pascalbetz** [comment]
thanks, @ankane
