### ISSUE TITLE
Combining multiple "values" with weights

### ISSUE THREAD

**Issue by jesster2k10** [ankane/disco#2]
Is it possible to use the implicit feedback recommendation system, where you specify a "value" but that value is based off of a number of different values, with weights.

It's still unclear to me how the "value" option works, in terms of the ranking. Does a higher value mean a user "likes" this item more or what's the correlation.

In my particular scenario, I'm trying to do:

1. Recommend product categories to users
3. Recommend users to users

And what I considered to be my inputs for the values are:

- likes: number of times I've hearted products in this category
- page_views: number of times I've viewed products in this category
- purchase_count: number of times I've purchased products in this category

If I wanted to combine the values for the three parameters I noted above, with particular weights, say on the `purchase_count` how exactly would this be possible/what suggestions would you make?

**Comment by jesster2k10** [comment]
I was looking at some other gems, and I suppose the best example to what I was trying to explain was the predictor gem https://github.com/Pathgather/predictor in the way you set up an input-matrix with the assigned weights

**Comment by ankane** [comment]
Hey @jesster2k10, a higher value indicates a stronger preference. I'm not familiar with the best way to combine values (typically you want an algorithm to learn the weights), but you can try manually combining them to see how that goes (`value = page_views + 10 * likes + 100 * purchase_count`).

If you find a better way, please let me know!
