### ISSUE TITLE
Ability to explicitly set range (error: comparison of float with 0 failed)

### ISSUE THREAD

**Issue by ztcollazo** [ankane/disco#20]
I just want to start by saying that I love this gem. Thanks, @ankane, for all of your work on it.

Recently, I've been building a recommendation system for a small project that I'm working on. I set `top_items` to `true` so that my top items can be more accurate, instead of just sorting by average review. Right now, just for testing, I have a small number of items (n < 10) with a review range of 1 to 5. I went in and manually added reviews to each of the items for a couple of different test users. After the first three reviews (one item with a 4 and 5 star and another with a 5 star), I kept getting the error `Comparison of float with 0 failed` when calling `top_items`. I fiddled around with more reviews by giving another item a review. I changed the rating for the review to a couple of different numbers, just to see if that would fix anything. Once I changed the rating to 4 or less, the error went away. From my inspection of disco's code and a few guesses, I'm assuming that there are requirements for the range of reviews that are not met by only having two possible numbers because the `min_rating` and `max_rating` are inferred based on the min and max of the training set. To fix this, I believe that it could be beneficial to be able to set `min_rating` and `max_rating` on the initialization of `Disco::Recommender`. This would help projects that are just kicking off not to run into unexpected errors. Would this be possible? Thank you!

**Comment by ankane** [comment]
Hey @ztcollazo, thanks for reporting!

I'm thinking of switching to [this approach](https://www.evanmiller.org/ranking-items-with-star-ratings.html) for top items in 0.3.0, which would require a list of ratings, like `[1, 2, 3, 4, 5]`, instead of just min/max. For now, forking and adding `min_rating` and `max_ratings` options should solve it.

**Comment by ankane** [comment]
Sorry for the noise, just pushed a fix that'll get rid of the error while keeping items in the correct order.
