### ISSUE TITLE
Getting similar users based on item

### ISSUE THREAD

**Issue by markfili** [ankane/disco#22]
~Hi, is it possible to store similar users after training and fetching them using the `recommender.similar_users(:user_id)` method similar to storing recommended items/products?~
Hi again, what I asked above was not really my issue but it would help in getting similar users when searching through recommended items with an item_id. Do you have any suggestion on how to achieve that?
What I have in mind is the following:
```
training_data = ...
recommender.fit(training_data)
recs = recommender.item_recs(item_id)
# the following part is missing
similar_users = ??
```
I'm looking for something like:
```
similar_users = recommender.similar_users_for_item(:user_id, :item_id)
```
that would combine item_recs and similar_users and return only user_ids

**Comment by ankane** [comment]
Hey @markfili, I'm not sure I understand the use case, but I think the closest you could get to similar users for a specific item would be users with the closest predicted rating, so you could use `predict` to get the rating for each user for that item, and then sort them by the absolute value of the difference from the predicted rating of the original user.

**Comment by markfili** [comment]
Hi @ankane thank you for you response. 

In this case the users don't rate the movies (yet) so `predict` doesn't return anything comparable.

Also in this case, the item in question is not yet in users's items - recommender was not trained with data that connects that user with that item - the user is just trying to see which users also liked what he liked + that one item that's not in his items.

What I see is that in order to get similar users for a user that's just "browsing" an item is to temporarily add that "browsed" item to user's items and then retrain the recommender to get similar users but I think that would be too much to do every time an item is "browsed" as the user and item count is growing through time.

Any thoughts?

And, sorry if I'm still unclear, it's a bit odd request, I know, but thank you nevertheless.

**Comment by ankane** [comment]
I still don't totally follow the use case, but Disco only works for offline recommendations right now, so you'll probably need to use another gem for online/real-time.

**Comment by markfili** [comment]
Ok, thank you for your answers and your work on this library.
I think I will try to use items as users and users as items and see if that works for my case which is that items recommend users, not the other way around or how this library was imagined. It might sound weird but I think it could work.
