### ISSUE TITLE
Questions on whether this gem can help me with my problem

### ISSUE THREAD

**Issue by vitobotta** [ankane/disco#23]
Hi! I can't believe how many awesome gems I am finding authored by you, you are a machine :D

I have a problem that I would like to solve with machine learning, also to learn this subject (I still know close to zero about it).

It's about recommendations. But not like "recommended products for a user", rather "recommended users for a given user".

So I have an app that manages users with their interests, and these users can have meetings between each two of them. These meetings can have different statuses like accepted, pending, declined etc.

I would like to be able to pick a user, and recommend to them other users that might be worth contacting for a meeting because they have compatible interests/intents.

So 

- each user can have one or more interests such as "Investments", "Jobs", etc and intents such as "Looking for..." or "Offering". So for example if a user is looking for an investment and another one is offering an investment. The two users have "compatible" interests
- I would consider for the training each group of { target interest, target intent, user, meetings ranking } where
  - target interest and intent are those of the user I want the recommendations for (so if I want recommendations for User X, I would do this for each of their interest/intent )
  - user would be any other user in the database (I would filter those with compatible interests and intents to the target ones)
  - ranking would be a number calculated depending on the statuses of meetings arranged by the user in the group with users having the target interests and intents. So for a group say that I find 10 meetings arranged with people with the target interest/intent, and let's say that I assign 10 points for accepted meetings, 8 for rescheduled, 6 for pending and 0 for cancelled or something like that. The ranking would be the sum of the points for all the user's meetings.
- the recommendation would then include the users with the highest ranking for the target interest/intent

Would this problem be solvable with this gem? If yes, would you mind giving me pointers on how exactly?

Thanks a lot in advance for any help. I am new to this so I am still wrapping my head around with the many possibilities.

**Comment by ankane** [comment]
Hey @vitobotta, unfortunately, I don't have the bandwidth to help, but I'd try seeing how others have approached similar problems.
