### ISSUE TITLE
Error while running bundle install

### ISSUE THREAD

**Issue by gmverdon** [ankane/disco#29]
An error occurred while installing numo-narray (0.9.2.0), and Bundler cannot continue.

In Gemfile:
  disco was resolved to 0.4.0, which depends on
    numo-narray

**Comment by ankane** [comment]
Hi @gmverdon, the output should have more information about the specific error.

**Comment by Mitcheljager** [comment]
I ran into the same issue but resolved it by upgrading disco to 0.4.2
