### ISSUE TITLE
user_recs returns recommendations that a user already knows

### ISSUE THREAD

**Issue by librod89** [ankane/disco#6]
I want to use disco to compare users that each have a list of services. For example:

User A has Services [1,2,3,4]
User B has Services [3,4,5,6]

If I put this data into the recommender and try to get the user recs for A, I would expect it to return _only_ services [5, 6] because User A already knows about [3, 4]. But it instead returns some services that the user knows about as well as some new services. So it's half working the way I would expect.

Does your algorithm ignore what a user already knows about according to the data given to `recommender.fit`?

**Comment by ankane** [comment]
Hey @librod89, thanks for reporting! Was a bug with the code. Will push out a new release shortly.
