### ISSUE TITLE
Global Item Rank

### ISSUE THREAD

**Issue by theianjones** [ankane/disco#8]
This may be a question out of ignorance, but given ranking items with explicit feedback, is there a way to get disco to generate a global rank for all the items.

So basically "top 10 ranked items" given the factors that are produced. 

Do the factors produced indicate rank without specifying an id?

Im wondering if a query like this makes sense:

```
	items.id
FROM
	items
WHERE
	items.neighbor_vector IS NOT NULL
ORDER BY
	items.neighbor_vector <-> CUBE (ARRAY [1, 1, 1, 1, 1, 1, 1, 1])
```

**Comment by ankane** [comment]
Hey @theianjones, you'd probably want to use Wilson score to generate overall top items. https://github.com/instacart/wilson_score#star-ratings

Relevant read: https://www.evanmiller.org/how-not-to-sort-by-average-rating.html

**Comment by theianjones** [comment]
Awesome. Thanks for the suggestion! 

Thanks for all the work you do. We use many of your gems over at egghead.io 😄

**Comment by ankane** [comment]
No problem. This seems like a useful feature for Disco, so will add it this weekend.

**Comment by ankane** [comment]
Just pushed a new release with a `top_items` method.

**Comment by theianjones** [comment]
Awesome! Im excited to take a look.
