### ISSUE TITLE
Disco v0.2.5 item_recs does not return related items

### ISSUE THREAD

**Issue by librod89** [ankane/disco#9]
Hello,

I am trying to upgrade to v0.2.5, but doing so breaks some tests that were originally passing in the previous version. Here is a simplified version of what I'm doing:

```
data = [{:user_id=>952, :item_id=>2057}, {:user_id=>952, :item_id=>2060}, {:user_id=>953, :item_id=>2063}]
recommender = Disco::Recommender.new(factors: 50)
recommender.fit(data)
```

As you can see, user 952 has items 2057 and 2060. So if I pass in item 2057, I would expect the recommender to return 2060.

```
recommender.item_recs(2057).pluck(:item_id)
```

But this returns `[2057, 2063]`. It returns itself and the non-related item. Am I doing something wrong here?

**Comment by ankane** [comment]
Hey @librod89, thanks for reporting! Just pushed out a new release with a fix.
